version: '3.8'

services:
  nestapp:
    container_name: room-planner-backend
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 4000:4000
    depends_on:
      - mongodb

  mongodb:
    container_name: database
    image: mongo
    restart: always
    ports:
      - "27017:27017"
